version: "3.9"

services:

  configserver:
    image: nikhildr/configserver:latest
    mem_reservation: 700m
    ports:
      - "8071:8071"
    networks:
      - skyfall-network

  eurekaserver:
    image: nikhildr/eurekaserver:latest
    mem_reservation: 700m
    ports:
      - "8070:8070"
    networks:
      - skyfall-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071 

  accounts:
      image: nikhildr/accounts:latest
      mem_reservation: 700m
      ports:
        - "8081:8081"
      networks:
        - skyfall-network
      depends_on:
        - configserver
        - eurekaserver
      deploy:
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
      environment:
        SPRING_PROFILE_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/ 


  cards:
    image: nikhildr/cards:latest
    mem_reservation: 700m
    ports:
      - "8083:8083"
    networks:
      - skyfall-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      

  loans:
    image: nikhildr/loans:latest
    mem_reservation: 700m
    ports:
      - "8082:8082"
    networks:
      - skyfall-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


networks:
  skyfall-network:
